# Generated by Django 3.2.8 on 2021-10-24 17:29

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form_id', models.CharField(max_length=44)),
                ('sheet_id', models.CharField(max_length=44)),
                ('sheet_gid', models.CharField(max_length=10)),
                ('font_size', models.IntegerField()),
                ('gym_plan', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/lloos/OneDrive - bwedu/Projects/pythonAnywhere/pythonAnywhere/bouldern/resources'))),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectionBoundaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_from', models.FloatField()),
                ('x_to', models.FloatField()),
                ('y_from', models.FloatField()),
                ('y_to', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bouldern.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='boundaries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bouldern.sectionboundaries'),
        ),
        migrations.AddField(
            model_name='section',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bouldern.gym'),
        ),
    ]
