# Generated by Django 3.2.8 on 2021-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouldern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_plan',
            field=models.ImageField(upload_to=''),
        ),
    ]
