# Generated by Django 3.2.8 on 2021-10-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouldern', '0002_alter_gym_gym_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_plan',
            field=models.ImageField(max_length=256, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
